### ISSUE TITLE
AutoCrafters keep popping into my inventory? 

### ISSUE THREAD

**Issue by goblinboii** [dthigpen/dtcraft-datapacks#6]
Autocrafters keep poping into my inventory, how do i stop that?

**Comment by goblinboii** [comment]
Had a datapack that unlocks all recipes which was causing a loop lol

**Comment by dthigpen** [comment]
Ah I could see that. It's been a while since I've looked at these datapacks but if I recall correctly, the logic for crafting custom items involves giving a player a recipe or advancement then taking it away. So the Autocraft datapack would see that the user unlocked it, gives them the custom item, removes the recipe or advancement, then the other datapack gives it back, causing the loop.

When I get back into datapack development I will see if I can improve the method, there is likely something better by now. Thanks for finding that out!
